### ISSUE TITLE
关于lang语言文件en和zh的最后一行未汉化留空的报告。

### ISSUE THREAD

**Issue by Fate-Time** [vfyjxf/BetterCrashes#1]
在en_US.lang的第23行是"bettercrashes.initerrorscreen.paragraph3.line4=can keep playing despite the crash."
而zh_CN.lang的第23行却是"bettercrashes.initerrorscreen.paragraph3.line4="等号后面是留空的。

与此同时我对比en_US.lang和zh_CN.lang的第22行，发现汉化发生了错行。具体如下：
bettercrashes.initerrorscreen.paragraph3.line3=and copy its link to clipboard. Since BetterCrashes is installed, you
bettercrashes.initerrorscreen.paragraph3.line3=由于安装了BetterCrashes，尽管发生了崩溃，你仍然可以继续进行游戏。

嗯，也不知道这算不算是汉化错误，就先报告一下。

**Comment by vfyjxf** [comment]
这个其实因为中文表达出来占用的空间比较少，第四行就不必要了，你可以对照下VanillaFix的语言文件，其实也是最后一行留空，翻译其实是完全翻译了
