### ISSUE TITLE
readme Grimoire依赖跳转错误(?)

### ISSUE THREAD

**Issue by xx146542xx** [vfyjxf/BetterCrashes#5]
添加了[CrucibleMC/Grimoire-legacy](https://github.com/CrucibleMC/Grimoire-legacy)的无法识别 forge提示缺失前置
使用[Aizistral-Studios/Grimoire](https://github.com/Aizistral-Studios/Grimoire)的才行

**Comment by vfyjxf** [comment]
其实我推荐用UniMixins，以及这个项目实际上已经废弃了，我基本上不管了，只是没有存档而已。
