### ISSUE TITLE
i just added this mod and grimoire mod but fml cannot load it

### ISSUE THREAD

**Issue by somerui** [vfyjxf/BetterCrashes#6]
Forge Mod Loader has found a problem with your minecraft installation
The mods and versions listed below could not be found
grimoire any
The file 'logs/fml-client-latest.log'contains more information
[fml-client-latest.log](https://github.com/vfyjxf/BetterCrashes/files/14080145/fml-client-latest.log)

**Comment by vfyjxf** [comment]
This mod is dead, try gtnh's fork.
